status = off

rootLogger.level = OFF
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = console

logger.spark.name = org.apache.spark
logger.spark.level = OFF
logger.spark.additivity = false

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = OFF
logger.hadoop.additivity = false

logger.jetty.name = org.eclipse.jetty
logger.jetty.level = OFF
logger.jetty.additivity = false

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %msg%n
